name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages:    write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build:css

      - name: Build Eleventy
        run: npx eleventy

      - name: Fix asset URLs for project path
        run: |
          # turn href="/style.css"  →  href="/TriStar/style.css"
          grep -Rl 'href="/style.css"' dist/ \
            | xargs sed -i 's|href="/style.css"|href="/TriStar/style.css"|g'
          # turn src="/js/…  →  src="/TriStar/js/…
          grep -Rl 'src="/js/' dist/ \
            | xargs sed -i 's|src="/js/|src="/TriStar/js/|g'
          # turn img URLs too if needed
          grep -Rl 'src="/img/' dist/ \
            | xargs sed -i 's|src="/img/|src="/TriStar/img/|g'
          # turn href="/personal"  →  href="/TriStar/personal"
          grep -Rl 'href="/personal"' dist/ \
            | xargs sed -i 's|href="/personal"|href="/TriStar/personal"|g'
          # turn href="/family"  →  href="/TriStar/family"
          grep -Rl 'href="/family"' dist/ \
            | xargs sed -i 's|href="/family"|href="/TriStar/family"|g'      
          # turn href="/benefits"  →  href="/TriStar/benefits"
          grep -Rl 'href="/benefits"' dist/ \
            | xargs sed -i 's|href="/benefits"|href="/TriStar/benefits"|g'
          # turn href="/beneficiaries"  →  href="/TriStar/beneficiaries"
          grep -Rl 'href="/beneficiaries"' dist/ \
            | xargs sed -i 's|href="/beneficiaries"|href="/TriStar/beneficiaries"|g'
          # turn href="/summary"  →  href="/TriStar/summary"
          grep -Rl 'href="/summary"' dist/ \
            | xargs sed -i 's|href="/summary"|href="/TriStar/summary"|g'
          # turn href="/upload"  →  href="/TriStar/upload"
          grep -Rl 'href="/upload"' dist/ \
            | xargs sed -i 's|href="/upload"|href="/TriStar/upload"|g'                                                                      

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          allow_empty_commit: true
