name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages:    write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build:css

      - name: Build Eleventy
        run: npx eleventy

      # ────────────────────────────────────────────────────────────────────
      # NEW STEP: Move everything into the `TriStar/` subfolder
      # ────────────────────────────────────────────────────────────────────
      - name: Nest site under /TriStar
        run: |
          mkdir -p dist/TriStar
          # move all files & folders (including hidden) into that subfolder
          shopt -s dotglob && mv dist/* dist/TriStar/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # now point at the nested folder so its contents become the site root
          publish_dir: ./dist/TriStar
          publish_branch: gh-pages
          allow_empty_commit: true
