name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages:    write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build:css

      - name: Build Eleventy
        run: npx eleventy

      - name: Fix asset URLs for project path
        run: |
          # turn href="/style.css"  →  href="/TriStar/style.css"
          grep -Rl 'href="/style.css"' dist/ \
            | xargs sed -i 's|href="/style.css"|href="/TriStar/style.css"|g'
          # turn src="/js/…  →  src="/TriStar/js/…
          grep -Rl 'src="/js/' dist/ \
            | xargs sed -i 's|src="/js/|src="/TriStar/js/|g'
          # turn img URLs too if needed
          grep -Rl 'src="/img/' dist/ \
            | xargs sed -i 's|src="/img/|src="/TriStar/img/|g'
          # turn linkItem("/personal/  →  linkItem("/TriStar/personal/
          grep -Rl 'linkItem("/personal/' dist/ \
            | xargs sed -i 's|linkItem("/personal/|linkItem("/TriStar/personal/'
          # turn linkItem("/family/  →  linkItem("/TriStar/family/
          grep -Rl 'linkItem("/family/' dist/ \
            | xargs sed -i 's|linkItem("/family/|linkItem("/TriStar/family/'
          # turn linkItem("/benefits/  →  linkItem("/TriStar/benefits/
          grep -Rl 'linkItem("/benefits/' dist/ \
            | xargs sed -i 's|linkItem("/benefits/|linkItem("/TriStar/benefits/'
          # turn linkItem("/beneficiaries/  →  linkItem("/TriStar/beneficiaries/
          grep -Rl 'linkItem("/beneficiaries/' dist/ \
            | xargs sed -i 's|linkItem("/beneficiaries/|linkItem("/TriStar/beneficiaries/'
          # turn linkItem("/summary/  →  linkItem("/TriStar/summary/
          grep -Rl 'linkItem("/summary/' dist/ \
            | xargs sed -i 's|linkItem("/summary/|linkItem("/TriStar/summary/'
          # turn linkItem("/upload/  →  linkItem("/TriStar/upload/
          grep -Rl 'linkItem("/upload/' dist/ \
            | xargs sed -i 's|linkItem("/upload/|linkItem("/TriStar/upload/'                      

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          allow_empty_commit: true
