name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages:    write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build:css

      - name: Build Eleventy
        run: npx eleventy

      - name: Nest site under /TriStar
        run: |
          mkdir -p dist/TriStar
          for item in dist/*; do
            # skip the TriStar folder itself
            if [ "$item" = "dist/TriStar" ]; then
              continue
            fi
            mv "$item" dist/TriStar/
          done

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist/TriStar
          allow_empty_commit: true
