name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages:    write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build CSS
        run: npm run build:css

      - name: Build Eleventy
        run: npx eleventy

      - name: Patch every leading-slash URL to /TriStar/
        run: |
          # Look through all .html and .js files in dist/
          find dist -type f \( -name '*.html' -o -name '*.js' \) -print0 \
            | xargs -0 sed -i \
                -e 's|href="/|href="/TriStar/|g'   \
                -e 's|src="/|src="/TriStar/|g'     \
                -e 's|fetch("/|fetch("/TriStar/|g' 

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          allow_empty_commit: true
